name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/@checkoutv4
      - uses: actions/@setup-nodev4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: Check styles
        run: npm run eslint
