name: Url Health Check

on:
  schedule:
    - cron: "59 23 * * *"
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-url-health:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        if: ${{ github.event_name == 'push' }}
        uses: Jtalk/url-health-check-action@v4
        with:
          url: "http://localhost:5000/"
