name: Url Health Check

on:
  schedule:
    - cron: "* * 1 * *"
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-url-health:
    runs-on: ubuntu-20.04
    steps:
      - name: Url check health
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'https://full-stack-open-pokedex-vric.onrender.com/health'
          max-attempts: 3