name: Url Health Check

on:
  schedule:
     - cron: "*/10 * * * *"
    #- cron: "59 23 * * *"
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-url-health:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - run: npm run install
      - run: npm run build
      - name: Url check health
        uses: jtalk/url-health-check-action@v4
        with:
          url: 'http://localhost:5000'
          max-attempts: 3