name: Url Health Check

on:
  schedule:
     - cron: "*/10 * * * *"
    #- cron: "59 23 * * *"
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  check-url-health:
    runs-on: ubuntu-20.04
    env:
      URL: "http://localhost:5000"
      METHOD: GET
    steps:
      - id: ping
        uses: sisodiya2421/pinger@v3
